### ISSUE TITLE
Does not work for Nullable enums

### ISSUE THREAD

**Issue by Nytra** [badhaloninja/EnumDropdown#2]
For example a ValueField with type "System.Nullable`1[[FrooxEngine.ShadowType, FrooxEngine]]"

No enum dropdown appears and there is a NullReferenceException in the log.

**Comment by Banane9** [comment]
Just looked over this and it's a doozy... it's gonna take some rewriting probably, as the current way the value gets assigned isn't amazingly easily extendable for it

**Comment by badhaloninja** [comment]
I just realized I had a completed commit stashed from before the Better flag support commit 7d460ab03150ff6ad41f379d8bbf551a9eaa137e, I tested it a bunch and it seems to work fine 

Added in [v1.2.0](https://github.com/badhaloninja/EnumDropdown/releases/tag/v1.2.0)
