### ISSUE TITLE
Can't connect ValueInputs to Writes/DynamicWrites/ImpulseWithDatas that match Types

### ISSUE THREAD

**Issue by CatSharkShin** [badhaloninja/EnumDropdown#7]
- When I spawn a Write/DynamicWrite<Chirality > for example Chirality I can create a ValueInput from the Write, but I can't connect it to the Write node.
- If I create a Write or DynamicWrite for a Type that's different from my ValueInput's Type, and I connect it, the Write/DynamicWrite changes and will work with the ValueInput.
- I've tryied DynamicWrite,Write,DynamicImpulseWithData, and for enums I've tried Chirality,Key,BodyNode
Video showcasing this:
https://github.com/badhaloninja/EnumDropdown/assets/53709818/41556d7b-aa54-49a6-99e9-15a4997ec3dc

**Comment by badhaloninja** [comment]
Could you upload a log of this happening? I will try to replicate this later today.

**Comment by badhaloninja** [comment]
I have not been able to reproduce this, does this still happen with v2.1.1?

**Comment by CatSharkShin** [comment]
Seems like its all good now! Amazing! And thank you for the mod ^^

**Comment by CatSharkShin** [comment]
Seems like its all good now! Amazing! And thank you for the mod ^^
